### PR TITLE
fix macos menu

### PR DESCRIPTION
**Pull request by devernay**
macOS was missing the File menu

### CODE REVIEW

**Comment by Rodeoclash** [comment]
Thanks for this. I don't actually own a mac and so can't test this, instead, do you mind just posting a screenshot of what it looks like?

**Comment by devernay** [comment]
without the fix: no File menu
image

with the fix: yeah!
image

I wanted to emphasize that Vodon Pro was the only standalone solution for video review, and it's great.
I'm not using it for gaming (I'm one of the authors of [Natron, a VFX/video compositing software](https://natrongithub.github.io/)), but it's really a nice piece of software! Super useful.

**Comment by Rodeoclash** [comment]
Thanks! I just wanted to make sure you'd had it running locally to test it. I'll cut a release now with the menu changes.

Natron looks great, I wouldn't mind having a chat with you about it at some point if you're up for an email exchange. I was exploring going native with the next version of Vodon Pro (QT + GStreamer to power it) but I've ultimately decided to build a browser native version of the app now that the FileSystem API can support storing videos and returning handles for them.

If you're interested in following along, the new version is being built at: https://github.com/Rodeoclash/vodon-player

**Comment by Rodeoclash** [comment]
@devernay I had a couple of Typescript errors in your code which I've resolved, however I can't test.

Do you mind seeing if the pre-release I've built here works correctly for you?

https://github.com/Rodeoclash/vodon-pro/releases/tag/v1.9.11

The changes in particular are: https://github.com/Rodeoclash/vodon-pro/commit/d3908aac2d746909100d39bf1d7af23682d82ddd

**Comment by devernay** [comment]
ok 👀

**Comment by devernay** [comment]
This works great, thank you @Rodeoclash !
One feature we would like, in order to share the Vodon projects with other people, would be to try to load video files from the same directory as the project if the given full path desn't exist. That way, we could package the json and the videos in the same directory.

**Pull request merged**
